USE [master]
GO

/****** Object:  Database [Library]    Script Date: 06/08/2016 14:53:18 ******/
CREATE DATABASE [Library] ON  PRIMARY 
( NAME = N'Library', FILENAME = N'd:\Documents\Visual Studio 2015\Projects\MVC_Library\MVC_Library\App_Data\Library.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Library_log', FILENAME = N'd:\Documents\Visual Studio 2015\Projects\MVC_Library\MVC_Library\App_Data\Library_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Library] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Library].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Library] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Library] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Library] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Library] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Library] SET ARITHABORT OFF 
GO

ALTER DATABASE [Library] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Library] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Library] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Library] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Library] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Library] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Library] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Library] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Library] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Library] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Library] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Library] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Library] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Library] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Library] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Library] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Library] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Library] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Library] SET  READ_WRITE 
GO

ALTER DATABASE [Library] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Library] SET  MULTI_USER 
GO

ALTER DATABASE [Library] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Library] SET DB_CHAINING OFF 
GO

USE [Library]
GO

/****** Object:  Table [dbo].[Authors]    Script Date: 06/08/2016 14:53:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Authors](
	[AuthorId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](MAX) NOT NULL,
	[Country] [varchar](MAX) NULL,
 CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED 
(
	[AuthorId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [Library]
GO

/****** Object:  Table [dbo].[Books]    Script Date: 06/08/2016 14:53:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Books](
	[BookId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](MAX) NOT NULL,
	[Year] [decimal](18, 0) NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED 
(
	[BookId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Books] ADD  CONSTRAINT [DF_Books_Quantity]  DEFAULT ((1)) FOR [Quantity]
GO

USE [Library]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 06/08/2016 14:53:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](MAX) NULL,
	[Email] [varchar](MAX) NOT NULL,
	[Password] [varchar](50) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO

ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Users]
GO

USE [Library]
GO

/****** Object:  Table [dbo].[BookAuthors]    Script Date: 06/08/2016 14:53:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BookAuthors](
	[BookId] [int] NOT NULL,
	[AuthorId] [int] NOT NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BookAuthors]  WITH CHECK ADD  CONSTRAINT [FK_BookAuthors_Authors] FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Authors] ([AuthorId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BookAuthors] CHECK CONSTRAINT [FK_BookAuthors_Authors]
GO

ALTER TABLE [dbo].[BookAuthors]  WITH CHECK ADD  CONSTRAINT [FK_BookAuthors_Books] FOREIGN KEY([BookId])
REFERENCES [dbo].[Books] ([BookId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BookAuthors] CHECK CONSTRAINT [FK_BookAuthors_Books]
GO

USE [Library]
GO

/****** Object:  Table [dbo].[BooksTaken]    Script Date: 06/13/2016 11:52:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BooksTaken](
	[UserId] [int] NOT NULL,
	[BookId] [int] NOT NULL,
	[Date] [date] NOT NULL,
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BooksTaken]  WITH CHECK ADD  CONSTRAINT [FK_BooksTaken_Books] FOREIGN KEY([BookId])
REFERENCES [dbo].[Books] ([BookId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BooksTaken] CHECK CONSTRAINT [FK_BooksTaken_Books]
GO

ALTER TABLE [dbo].[BooksTaken]  WITH CHECK ADD  CONSTRAINT [FK_BooksTaken_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BooksTaken] CHECK CONSTRAINT [FK_BooksTaken_Users]
GO


